# Generated by Django 5.1.5 on 2025-02-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fan',
            options={'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='ustoz',
            options={'verbose_name_plural': 'Ustozlar'},
        ),
        migrations.AlterModelOptions(
            name='yonalish',
            options={'verbose_name_plural': 'Yonalishlar'},
        ),
    ]
